version: '3'

services:
  postgres:
    image: 'postgres:9-alpine'
    volumes:
      - ./postgres:/var/lib/postgresql/data

  server:
    build: ./
    command: sh /home/app/start.sh
    ports:
      - '3000:3000'
    volumes:
      - ./:/home/app
    links:
      - postgres
